version: '3.8'

services:
  part5:
    build: ../part_5/
    container_name: server

  nginx_proxy:
    image: nginx
    ports:
      - "80:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - part5
